### PR TITLE
refactor: Attempt to make web output easier to read

### PR DESCRIPTION
**Pull request by rschristian**
Just some quick thoughts, absolutely feel free to close this.

The lack of margins & consistent table width makes this quite hard to read in my opinion. Felt like it needed a bit of breathing room & set width on the tables.

This change does, however, cause some extra wrapping in the table cells. I think this is a worthy trade off, but something to note.

### CODE REVIEW

**Comment by titoBouzout** [comment]
Thanks, with table fixed looks better, I am not sure of the width constrain, but I also do not mind

**Comment by rschristian** [comment]
Fair enough -- certainly might need additional fiddling with the styles yet. As mentioned, I did this quick. Similar breakpoints/limits for 768/1024/1536px might be a good idea.

Super niche, but I use an ultrawide monitor which colored my choices here a bit. If we were to limit the width to say 90%, as most do want _some_ margin, you'd get this:

Web view from ultrawide monitor, 3440x1440

This isn't my typical view when dev'ing, then I will use two windows side-by-side, but the width of the table was a bit extreme if I do go full-width (which I will when just browsing around). Very low density, have to physically turn my head just to read across a row. Hence why I think some width constrain is useful, but this particular one may need tweaking yet.

**Comment by titoBouzout** [comment]
All makes sense, thanks for the improvements

**Comment by titoBouzout** [comment]
@rschristian I have added settings to make the table fixed or not, also to toggle data fields and table size

**Pull request merged**
